### ISSUE TITLE
[Server Components] Gestion des cas sans certificats

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/site#1055]

**Comment by johangirod** [comment]
> page /certificat is broken (currently only displaying an error on Qualibat which can create a false impression that every company is Qualibat)

I'm curious how you would do that otherwise ? The only alternatives that comes to my mind are : 
- Adding a logic for knowing beforehand that the company has a Qualibat certificat (by putting the info in the search API ?)
- Not showing Datasection when a route has errored, but that would mean false negative, which is worse in my opinion.
